# Generated by Django 5.2.10 on 2026-01-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpost',
            name='image',
        ),
    ]
