# Generated by Django 5.2.10 on 2026-01-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AspectInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_1', models.CharField(max_length=20)),
                ('planet_2', models.CharField(max_length=20)),
                ('aspect_type', models.CharField(choices=[('Conjunction', 'Conjunction (0)'), ('Opposition', 'Opposition (180)'), ('Trine', 'Trine (120)'), ('Square', 'Square (90)'), ('Sextile', 'Sextile (60)')], max_length=20)),
                ('text_en', models.TextField()),
                ('text_tr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanetInterpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet', models.CharField(choices=[('Sun', 'Sun'), ('Moon', 'Moon'), ('Mercury', 'Mercury'), ('Venus', 'Venus'), ('Mars', 'Mars'), ('Jupiter', 'Jupiter'), ('Saturn', 'Saturn'), ('Uranus', 'Uranus'), ('Neptune', 'Neptune'), ('Pluto', 'Pluto')], max_length=20)),
                ('sign', models.CharField(choices=[('Aries', 'Aries'), ('Taurus', 'Taurus'), ('Gemini', 'Gemini'), ('Cancer', 'Cancer'), ('Leo', 'Leo'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Scorpio', 'Scorpio'), ('Sagittarius', 'Sagittarius'), ('Capricorn', 'Capricorn'), ('Aquarius', 'Aquarius'), ('Pisces', 'Pisces')], max_length=20)),
                ('house', models.IntegerField(default=0, help_text='0 for generic sign interpretation, 1-12 for specific house')),
                ('text_en', models.TextField(help_text='English Interpretation')),
                ('text_tr', models.TextField(help_text='Turkish Interpretation')),
            ],
            options={
                'unique_together': {('planet', 'sign', 'house')},
            },
        ),
    ]
