# Generated by Django 5.2.10 on 2026-01-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.CharField(help_text='YYYY/MM/DD', max_length=10)),
                ('birth_time', models.CharField(help_text='HH:MM', max_length=5)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('sun_sign', models.CharField(blank=True, max_length=20)),
                ('moon_sign', models.CharField(blank=True, max_length=20)),
                ('asc_sign', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('New Moon', 'New Moon'), ('Waxing', 'Waxing'), ('Full Moon', 'Full Moon'), ('Waning', 'Waning')], max_length=20)),
                ('category', models.CharField(help_text='Beauty, Garden, Diet, Business', max_length=50)),
                ('text_en', models.TextField()),
                ('text_tr', models.TextField()),
            ],
        ),
    ]
