# Generated by Django 5.2.10 on 2026-01-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0002_celebrity_dailytip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planetinterpretation',
            name='planet',
            field=models.CharField(choices=[('Sun', 'Sun'), ('Moon', 'Moon'), ('Mercury', 'Mercury'), ('Venus', 'Venus'), ('Mars', 'Mars'), ('Jupiter', 'Jupiter'), ('Saturn', 'Saturn'), ('Uranus', 'Uranus'), ('Neptune', 'Neptune'), ('Pluto', 'Pluto'), ('Chiron', 'Chiron'), ('North Node', 'North Node')], max_length=20),
        ),
    ]
