# Generated by Django 5.2.10 on 2026-01-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0003_alter_planetinterpretation_planet'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHoroscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('summary_en', models.TextField()),
                ('summary_tr', models.TextField()),
                ('aspects', models.JSONField(default=list)),
            ],
        ),
    ]
