# Generated by Django 5.2.10 on 2026-01-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0006_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='membership_level',
            field=models.CharField(choices=[('free', 'Free'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='free', max_length=10),
        ),
    ]
