# Generated by Django 5.2.10 on 2026-01-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0007_userprofile_membership_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyHoroscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('sign', models.CharField(max_length=20)),
                ('text_en', models.TextField(blank=True)),
                ('text_tr', models.TextField(blank=True)),
                ('theme_en', models.CharField(blank=True, max_length=200)),
                ('theme_tr', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-start_date', 'sign'],
                'unique_together': {('start_date', 'sign')},
            },
        ),
    ]
