# Generated by Django 5.2.10 on 2026-01-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0008_weeklyhoroscope'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('image_url', models.CharField(default='https://images.unsplash.com/photo-1532968961962-8a0cb3a2d4f5?auto=format&fit=crop&w=800&q=80', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='membership_level',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10),
        ),
    ]
