# Generated by Django 5.2.10 on 2026-01-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0010_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Upload a custom image (overrides image_url)', null=True, upload_to='blog_images/'),
        ),
    ]
