# Generated by Django 5.2.10 on 2026-02-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0012_userprofile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
