# Generated by Django 5.2.10 on 2026-02-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0012_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhoroscope',
            name='signs_data',
            field=models.JSONField(blank=True, default=dict, help_text="{'aries': 'text', ...}"),
        ),
        migrations.AlterField(
            model_name='dailyhoroscope',
            name='aspects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='dailyhoroscope',
            name='summary_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyhoroscope',
            name='summary_tr',
            field=models.TextField(blank=True),
        ),
    ]
