# Generated by Django 5.2.10 on 2026-01-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyforecast',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='forecast_images/'),
        ),
    ]
